# Source: https://minecraft.fandom.com/wiki/Server.properties
allow-cheats=false
allow-list=false 
compression-threshold=1
content-log-file-enabled=false 
correct-player-movement=false 
default-player-permission-level=member 
difficulty=easy 
force-gamemode=false 
gamemode=survival 
level-name=Bedrock level 
level-seed=
level-type=DEFAULT 
max-players=10
max-threads=8
online-mode=true 
player-idle-timeout=30
player-movement-distance-threshold=0.3 
player-movement-duration-threshold-in-ms=500
player-movement-score-threshold=20
server-authoritative-block-breaking=false
server-authoritative-movement=server-auth 
server-name=Dedicated Server 
server-port=19132
server-portv6=19133
texturepack-required=false 
tick-distance=4
view-distance=32
